Repository jonathancede/filesystem-explorer, pull requests merged in 2021-06, with the labels that each got.

#10 initial aside design
  src/pages/main/main.css
  src/pages/main/main.php
Labels: design

#16 Feat/login page
  doc/img/28792.png
  doc/img/28814.png
  doc/img/29080.png
  doc/img/29122.png
  doc/img/29146.png
  doc/img/592965.png
  doc/img/csv.png
  doc/img/descargar.png
  doc/img/exe-icon.png
  doc/img/jpg.png
  doc/img/png-clipart-pdf-computer-icons-document-file-format-pdf-miscellaneous-text.png
  doc/img/png.png
  doc/img/powerpoint-icon-png-20.jpg
  doc/img/usecase.jpg
  doc/user_pictures/20200129_165746.jpg
  doc/user_pictures/User_Circle.png
  doc/user_pictures/user.png
  package.json
  root/erick/Archivo ppt.pptx
  root/erick/Archivo_pdf.pdf
  root/erick/DS4Updater.exe
  root/erick/Este es mi archivo ODT.odt
  root/erick/Folder/erick-file-folder.txt
  root/erick/Mi archivoooo en zip.zip
  root/erick/Mi archivoooo.txt
  root/erick/Tama Gucci  Lower My Shades.mp3
  root/erick/archivo_csv - Sheet1.csv
  root/erick/archivo_jpg.jpg
  root/erick/archivo_png.png
  root/erick/archivo_svg.svg
  root/erick/fvsdefvsdv/erick-file-folder.txt
  root/erick/otro archivoo en rar.rar
  src/index.php
  src/pages/custom.scss
  src/pages/login/login.css
  src/pages/login/login.php
  src/pages/login/login.scss
  src/pages/main/main.css
  src/pages/main/main.php
  src/php/local_files/read_local_files.php
  src/php/login/login-control.php
  src/php/login/login.php
  src/php/login/logout.php
  src/php/login/myDatabase.php
Labels: design, enhancement

#27 feat/ navbar file information done
  src/pages/login/login.php
  src/pages/main/main.css
  src/pages/main/main.php
  src/pages/modal-play/modal-play.php
  src/php/local_files/read_local_files.php
  src/php/navbar_file_information/file_info.php
  src/php/navbar_file_information/navbar_information.php
Labels: enhancement
